name: ci

on:
  push:
    branches:
      - "main"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD  }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            devopswithsam/githubactions:latest
            devopswithsam/githubactions:${{ github.run_number }}
      - name: Fetch k8smanifest repository
        uses: actions/checkout@v2
        with:
          repository: iam-sameera/githubactions-k8smanifest
          path: githubactions-k8smanifest
      - name: Update deployment YAML
        run: |
          sed -i "s|image: devopswithsam/githubactions:[0-9]*|image: devopswithsam/githubactions:${{ github.run_number }}|g" githubactions-k8smanifest/deploy.yml
      - name: Commit and push changes
        run: |
          cd githubactions-k8smanifest
          git config --global user.email "devopssameera@gmail.com"
          git config --global user.name "Sameera Dissanayaka"
          git add deploy.yml
          git commit -m "Update deployment image tag to ${{ github.run_number }}"
          git remote set-url origin https://$GITHUB_ACTOR:${{ secrets.PAT }}@github.com/iam-sameera/githubactions-k8smanifest.git
          git push origin main
